application:
  host: localhost
  port: 1111
fileStorage:
  directoryName: ./data
metaStorage:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  DBName: postgres
chunkSize: 1048576
loadWorkersCnt: 10
fetchWorkersCnt: 100